name: json schema lint

on:
  pull_request:
    paths:
      - .schema/*.json

jobs:
  lint-schema:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 22
      - run: npm install -g ajv-cli
      - run: ajv --spec draft2020 compile -s .schema/schema.json
        name: validate schema
      - run: ajv --spec draft2020 validate -s .schema/schema.json -d .schema/pkb.json
        name: lint example config
